language: rust
cache: cargo
before_script:
  - cargo install -f rustfmt --vers 0.7.1  # the 0.8.0 is buggy, for the moment we fix the version
  - export PATH=$PATH:$HOME/.cargo/bin
rust:
  - stable
  - beta
  - nightly

script:
  - cargo fmt -- --write-mode=diff
  - cargo test

matrix:
  allow_failures:
    - rust: nightly
